#+TITLE: Chapter 14: "I Always Do It Your Way!" The Subjugation Lifetrap
#+DATE: 2022-03-22T18:47:48+0530
#+DRAFT: true
#+LASTMOD: 2022-03-27T12:26:49+0530


TODO

* THE SUBJUGATION QUESTIONNAIRE

*DESCRIPTION*

1. I let other people control me.
2. I am afraid that if I do not give in to other people's wishes they will retaliate, get angry, or reject me.
3. I feel the major decisions in my life were not really my own.
4. I have a lot of trouble demanding that other people respect my rights.
5. I worry a lot about pleasing people and getting their approval.
6. I go to great lengths to avoid confrontations.
7. I give more to other people than I get back in return.
8. I feel the pain of other people deeply, so I usually end up taking care of the people I'm close to.
9. I feel guilty when I put myself first.
10. I am a good person because I think of others more than of myself.

*YOUR TOTAL SUBJUGATION SCORE:* _____

(Add your scores together for questions 1-10)

* THE EXPERIENCE OF SUBJUGATION

To a large degree, you experience the world in terms of control issues. Other people in your life always seem to be in control—you feel controlled
by the people around you. At the core of your subjugation is the conviction that you must please others, that you must please parents, brothers, sisters, friends, teachers, lovers, spouses, bosses, coworkers, children, and even strangers. In all likelihood, the only exception to this rule of pleasing people—the only person you do not feel obliged to please—is yourself. It is what the other person wants that comes first.  

One common theme in the lives of Carlton and Mary Ellen is the feeling of being /trapped/ in their lives. The feeling of subjugation is  oppressive. It is a burden to live life under the weight of that feeling. Constantly meeting the needs of other people is so much responsibility. It is  exhausting. Life loses much of its joy and freedom. Subjugation deprives you of your freedom because the choices you make are dictated by their effects on other people. Your focus is not on yourself. It is not, "What I want and feel," but rather, "What you want and what I can do to make you happy with me."

Subjugation robs you of a clear sense of what you want and need—of who you are. Carlton, who was hounded by his father since childhood to go into the family business and who obeyed, knows inside that he does not want to be a businessman, but has no idea of what he does want to be. He has never taken the appropriate steps to find out. You are passive. Life happens to you.


TODO

You feel that you cannot shape the course of events in your life. You feel trapped by circumstances or swept along by fate. Rather than an actor, you are a reactor. You feel there is little you can do to solve your problems. You merely wait and hope that suddenly, miraculously, everything will get better.

You probably think of yourself as the kind of person with whom it is easy to get along. Since you are so agreeable and eager to please, and tend to avert conflict, naturally you get along with others. You see yourself as someone who is willing to accommodate. You even might consider this one of your assets: that you are flexible and able to adjust to many types of people. But you have difficulty setting limits on the demands other people make of you. When people ask you to do things that are unreasonable, such as more than your share of the work, you say "yes." And you find it extremely difficult to ask other people to change their behavior, no matter how much their behavior disturbs you.

Similarly, you might feel proud that you are able to serve others—that you are able to help other people and be attentive to other people's needs. And you are right. The ability to be there for other people is a strength of self-sacrificing people. You probably have developed exemplary skills in helping others, and may be in one of the helping professions. However, one of your weaknesses is that what you want often gets lost. Too often you are unassertive and silent about your needs.

Your subjugation lowers your self-esteem. You do not feel entitled to the legitimate rights of all people in relationships. Everyone has rights except you. Erica expressed this about Carlton in one of our marital sessions.



#+BEGIN_VERSE
ERICA: /I was so mad at Carlton the other night./

THERAPIST: /What happened?/

ERICA: /We went out to eat, and when Carlton got his food, it was cold. But he wouldn't tell the waitress to take it back. He kept the food, and he ate it. And meanwhile he complained about it to me the whole night./

CARLTON: /It just seemed like such a trivial thing to make a big fuss over./
#+END_VERSE

We hear this argument often from subjugated patients: that they do not fight for what they want because their desires seem so trivial. But in the end, when you add all the trivial desires together, you are left with a life in which few of your needs are met.

When we first pointed out his subjugation to Carlton, he argued that he was not subjugated, he was simply easygoing. However, Carlton was /passive/ more than easygoing. Easygoing people have /some/ areas in which they have strong feelings, and will assert what they feel. In minor matters, they will not express opinions, but in major matters they usually will express themselves. They will stand up for certain things. In subjugation, there are almost no strong opinions across the board. Whether the issues are big or small—no matter what is at stake—in subjugation there is no strong sense of self. Unexpressed anger is another clue that you are subjugated rather than easygoing.

Because you lack a strong sense of self, of /who/ you are, there is the danger that you might lose yourself in your subjugator. You can become so immersed in trying to meet the needs of other people that you begin to blend or merge into these people. The boundary between who you are and who they are becomes blurred. You might adopt other people's goals and opinions as your own. You might adopt other people's values. You might lose yourself in the other. There is a chance that you might subjugate yourself to a group, particularly a group with a charismatic leader. You might even find some attraction to cult groups.

*Notes:* Useful points:

1. You lack a strong sense of self, of who you are.
2. *Danger:* You might lose yourself to your subjugator
3. You can become so inmmersed in trying to meet the needs of other people that you begin to blend or merge into these people.
4. The boundary between who you are and who they are becomes blurred.
5. You might adopt other people's goals and opinions as your own.
6. You might adopt other people's values.
7. You might lose yourself in the other.
8. You might subjugate yourself to a group, particularly a group with a charismatic leader.

In our work, we have identified two major reasons why subjugated patients allow other people to control them. The first is that they subjugate themselves out of /guilt/, or because they want to relieve the pain of others; and the second is that they subjugate because they anticipate rejection, retaliation, or abandonment. These reasons correspond to two types of subjugation.

-------------------
*Two Types of Subjugation*

1. Self-Sacrifice (subjugation out of guilt)
2. Submissiveness (subjugation out of fear)
------------------

Carlton subjugates himself out of guilt. He wants to gain approval. He wants everyone to like him. Gaining approval is his primary motivation. In addition, Carlton feels the pain of others very deeply. When he feels that another person is suffering, he is moved to take care of that person. He tries to meet other people's needs. Whenever he believes he has failed, he feels guilty. He finds the experience of guilt very uncomfortable, and his self-sacrifice helps him avoid this guilt.

Mary Ellen, on the other hand, subjugates herself out of fear. She submits because she is afraid of being punished. This fear is certainly realistic: Dennis is cruel and domineering. However, one wonders what it is about Mary Ellen that caused her to flee from one subjugated  relationship with her father into another one with her husband. In her marriage, Mary Ellen reenacts her childhood subjugation.


*** (1) Self-Sacrifice

Self-sacrificers feel responsible for the well-being of others. As a child, you may have experienced too much responsibility for the physical or  emotional welfare of a parent, sister, brother, or of some other close person. For example, you may have had a parent who was chronically ill or depressed. As an adult, you believe it is your responsibility to take care of others. In doing so, you neglect yourself.

TODO

*** (2) Submissiveness

Submission is the second form of the Subjugation lifetrap. You submit to the subjugation process involuntarily. Whether you actually have a choice or not, you feel as though you have no choice. As a child, you subjugated yourself in order to avoid punishment or abandonment, probably by a parent. Your parent threatened to hurt you or to withdraw love or attention. There was coercion in the subjugation process. You are almost always angry, even if you do not recognize your anger.    

    
TODO

* Origins of the Subjugation Lifetrap
1. Your parents tried to dominate or control almost every aspect of your life.
2. Your parent(s) punished, threatened, or got angry at you when you would not do things their way. 
3. Your parent(s) withdrew emotionally or cut off contact with you if you disagreed with them about how to do things.
4. Your parent(s) did not allow you to make your own choices as a child.
5. Because your mother/father was not around enough, or was not capable enough, you ended up taking care of the rest of the family.
6. Your parent(s) always talked to you about their personal problems, so that you were always in the role of listener.
7. Your parent(s) made you feel guilty or selfish if you would not do what they wanted.
8. Your parent(s) were like martyrs or saints—they selflessly took care of everyone else and denied their own needs.
9. You did not feel that your rights, needs, or opinions were respected when you were a child.
10. You had to be very careful about what you did or said as a child, because you worried about your mother's/father's tendency to become worried or depressed.
11. You often felt angry at your parent(s) for not giving you the freedom that other children had.

TODO

-----
*Changing Your Subjugation Lifetrap*

1. Understand your childhood subjugation. Feel the subjugated child inside of you.
2. List everyday situations at home and at work in which you subjugate or sacrifice your own needs to others.
3. Start forming your own preferences and opinions in many aspects of your life: movies, foods, leisure time, politics, current controversial issues, time usage, etc. Learn about yourself and your needs.
4. Make a list of what you do or give to others, and what they do or give to you. How much of the time do you listen to others? How much of the time do they listen to you?
5. Stop behaving passive-aggressively. Push yourself systematically to assert yourself—express what you need or want. Start with easy requests first.
6. Practice asking other people to take care of you. Ask for help. Discuss your problems. Try to achieve a balance between what you give and get.
7. Pull back from relationships with people who are too self-centered or selfish to take your needs into account. Avoid one-sided relationships. Change or get out of relationships where you feel trapped.
8. Practice confronting people instead of accommodating so much. Express your anger appropriately, as soon as you feel it. Learn to feel more comfortable when someone is upset, hurt, or angry at you.
9. Do not rationalize your tendency to please others so much. Stop telling yourself that it doesn't really matter. 
10. Review past relationships and clarify your pattern of choosing controlling or needy partners. List the danger signals for you to avoid. If possible, avoid selfish, irresponsible, or dependent partners who generate very high chemistry for you.
11. When you find a partner who cares about your needs, asks your opinions and values them, and who is strong enough to do 50 percent of the work, give the relationship a chance.
12. Be more aggressive at work. Take credit for what you do. Do not let other people take advantage of you. Ask for any promotions or raises you might be entitled to get. Delegate responsibilities to other people.
13. (To the Rebel.) Try to resist doing the opposite of what others tell you to do. Try to figure out what you want, and do it even if it is consistent with what authority figures tell you.
14. Make flashcards. Use them to keep you on track.

-----




* SOME FINAL WORDS

As you work to change, it is important to give some recognition to each bit of progress. Give yourself credit where it is due. Change is much harder when you forget to reward yourself for the steps along the way. Try to keep looking back at how far you have come, rather than looking forward to how far you have to go. When you make any change, no matter how slight, take a moment to feel good about it. As you take a step out of your subjugation, give yourself the acknowledgment you deserve.

Remember that your Subjugation lifetrap has the strength of a lifetime of memories and of a multitude of repetitions and confirmations that it is right. Subjugation feels right to you. Your lifetrap is central to your entire self-image and view of the world. Naturally, it is going to fight very hard for survival. You find comfort and reassurance in holding onto your life-trap, regardless of its negative consequences for your life. You should not become discouraged because change is slow.

It is tempting to berate yourself for your subjugation. Mary Ellen says, "I am such a wimp. It makes me hate myself." But this attitude can only hinder your efforts to change. Try to respect the reasons your lifetrap developed in the first place. In your childhood, it was essential for your emotional survival. But what was once a help to you is now hurting you, and it is time to give it up. It is time for you to begin the slow journey out of self-denial and self-defeat, and to reclaim your life for yourself.


