#+TITLE: Chapter 17: A Philosophy to Change
#+DATE: 2022-03-22T17:58:01+0530
#+DRAFT: true
#+lastmod: 2022-03-22T18:44:01+0530

* SEVEN BASIC ASSUMPTIONS

The process of change is a difficult one. We watch patients every day struggling to overcome deeply ingrained patterns. We also go through this same process of growth ourselves, and we observe how frustrating it can be to our friends and family members.

We know that self-help books, including this one, probably make change seem easier than it actually is. We wish there were some way to fully prepare you for the ups and downs of growing. We want you to expect change to be an erratic process. Patients always tell us that it's "one step forward and two steps back." There are many obstacles you can expect to encounter in trying to change. Chapter 5 describes many of them and offers solutions.

We have a philosophy underlying our approach to change that includes several basic assumptions. We have no way to prove these beliefs, except to say that we have found change easier when we assume these beliefs to be true. First, we believe that we all have a part of ourselves that wants to be happy and fulfilled. Sometimes this process is called self-actualization. We assume that this healthy self has somehow been buried under years of neglect, subjugation, abuse, criticism, and other destructive forces. The process of change involves reawakening this healthy side and giving its hope.

Second, we assume that /there are several basic "needs" or desires that will lead most of us to be happier if they are satisfied:/ the need to relate and feel connected to other people; the need for independence, for autonomy; the need to feel desirable, competent, successful, attractive, worthwhile—to be "good" people among our peers; the need to express what we want and feel to others, to assert ourselves; the need for pleasure, fun, creativity—to pursue interests, hobbies, and activities that gratify us; and the need to help others, to show concern and love. We will discuss these needs in more detail later in this chapter.

A third core assumption in the lifetraps approach is that people can change in very basic ways. Some people are skeptical about this process. They believe that our basic personality is determined by the end of childhood, or even earlier by our genetic makeup, and that major personality change in adulthood is impossible or unlikely. We firmly reject this idea. We see people change every day in very fundamental ways. However, we acknowledge that changing core patterns is extremely difficult. Our inherited temperament, along with our early family and peer experiences, create very powerful forces that act against change. However, while our childhood histories create strong obstacles to change, they do not make change impossible. The more destructive these early forces, the harder we will have to work to change lifetraps, and the more support we will need from others.

A fourth assumption is that we all have strong tendencies to resist core change. This belief has important implications. It implies that /it is highly unlikely that we will change basic lifetraps without making a conscious decision to do so/. Most of us operate on automatic pilot, repeating habits of thinking, feeling, relating, and doing what we have practiced over our lifetime. These patterns are comfortable and familiar, and we are very unlikely to change them unless we make a concerted, deliberate, and sustained effort to do so; if we wait for fundamental change to happen on its own, it almost certainly will not. We are doomed to repeat the mistakes of the past and legacy of our parents and grandparents unless we make intentional and prolonged efforts to alter them.

A fifth assumption is that most of us have strong inclinations to avoid pain. This is good and bad. The good news is that most of us gravitate toward experiences that bring us pleasure and gratification. The bad news is that /we avoid facing situations and feelings that cause us pain, even when confronting them might lead to growth/. This desire to avoid pain is one of the most difficult roadblocks to change. In order to modify core lifetraps, we must be willing to face painful memories that stir up emotions like sadness, anger, anxiety, guilt, shame, and embarrassment. We must be willing to face situations we have avoided much of our lives because we fear they will result in failure, rejection, or humiliation. Unless we face these painful memories and threatening situations, we are doomed to repeat patterns that hurt us. Most of us shy away from painful feelings; many patients leave therapy rather than face these emotions. People become addicted to alcohol and drugs to avoid these feelings. We must commit ourselves to facing pain in order to change.

Sixth, /we do not believe that any one technique or approach to change will be successful for all people/. We believe that the most effective change approaches will be those that integrate and pull together a variety of different strategies. In the lifetrap approach, we draw on cognitive,  behavioral, experiential, inner-child, psychoanalytic, and interpersonal  techniques to help you change. Because we are combining several powerful change agents, we believe that more people will be helped with this therapy than by other therapies that only utilize one or two of these interventions. We strongly urge you to seek out approaches and therapists that combine several models, instead of just one or two. Although we do not expect to help everybody with our lifetrap approach, we hope to be more successful than single-technique treatments.

* CREATING A PERSONAL VISION

Our final assumption about change involves the need to create a personal vision. Change is not just the absence of lifetraps. We must each discover who we want to be and what we want from life. We feel that it is vital to have this direction before going too far along the change process. We want you to look beyond the elimination of your individual lifetraps to an image of what will lead you finally to feel fulfilled, happy, and self-actualized.

Many of us go through life with only a fuzzy sense of where we are going. This explains why many of us reach middle-age or retirement feeling disappointed and disillusioned. We have never had a broad set of overriding goals to guide us. It would be like playing football without knowing where the goal posts are, or getting on a plane without knowing its destination. It is crucial for each of us to have such a blueprint. /The eleven lifetraps are obstacles to reaching our goals; they do not tell us what each of us uniquely needs to be happy/. Once you develop a set of life goals, you can begin to plan specific steps to get there. We urge you to approach change in a strategic way, not haphazardly.

TODO

* EMPATHIC SELF-CONFRONTATION

We have developed a term to describe what we consider to be a healthy attitude toward change: /empathic self-confrontation/. Show compassion for yourself, while continually pushing yourself to change. Many people either criticize themselves too harshly when they do not feel they have changed enough, or they are too lenient and make excuses to let themselves off the hook.

The process of change is very difficult, as we have stated repeatedly. Above all, be compassionate with yourself. You are struggling to do your best. Be understanding of your limitations and flaws. Remember that lifetraps are hard to change. It is vital that you remember how you became the way you are. /Remember the origins of your lifetraps, and try to empathize with yourself when you were a child/

However, it is also important to take responsibility for changing. Many self-help groups have been criticized for encouraging members to feel like victims of their parents without teaching them to take responsibility for changing. We think this is a serious risk. It is vital that you keep confronting yourself. Be persistent. Do not keep putting off change, waiting for a more convenient time. The best time to begin changing is now. No matter how damaged you were as a child, this does not excuse you from taking responsibility for change. /Childhood pain explains why change is so difficult and takes so long; it does not explain why someone allows destructive patterns to continue without working hard to alter them/.

TODO

* ENLISTING THE HELP OF OTHERS

It is hard to change alone. Change is easier when you have support. Reach out for help to the people who love you. Let friends and supportive family members get involved. Tell them what you are trying to do and enlist their assistance.

TODO




