---
title: "Chapter 36: Life as a Story"
date: 2022-03-12Sat19:58:25
draft: true
---

* Introduction

Early in the days of my work on the measurement of experience, I saw Verdi’s opera La Traviata . Known for its gorgeous music, it is also a moving story of the love between a young aristocrat and Violetta, a woman of the demimonde. The young man’s father approaches Violetta and convinces her to give up her lover, to protect the honor of the family and the marriage prospects of the young man’s sister. In an act of supreme self-sacrifice, Violetta pretends to reject the man she adores. She soon relapses into consumption (the nineteenth-century term for tuberculosis). In the final act, Violetta lies dying, surrounded by a few friends. Her beloved has been alerted and is rushing to Paris to see her. H Kto earing the news, she is transformed with hope and joy, but she is also deteriorating quickly.

*keys:* measurement of experience.

No matter how many times you have seen the opera, you are gripped by the tension and fear of the moment: Will the young lover arrive in time? There is a sense that it is immensely important for him to join his beloved before she dies. He does, of course, some marvelous love duets are sung, and after 10 minutes of glorious music Violetta dies.

On my way home from the opera, I wondered: Why do we care so much about those last 10 minutes? I quickly realized that I did not care at all about the length of Violetta’s life. If I had been told that she died at age 27, not age 28 as I believed, the news that she had missed a year of happy life would not have moved me at all, but the possibility of missing the last 10 minutes mattered a great deal. Furthermore, the emotion I felt about the lovers’ reunion would not have changed if I had learned that they actually had a week together, rather than 10 minutes. If the lover had come too late, however, La Traviata would have been an altogether different story. A story is about significant events and memorable moments, not about time passing. Duration neglect is normal in a story, and the ending often defines its character. The same core features appear in the rules of narratives and in the memories of colonoscopies, vacations, and films. This is how the remembering self works: it composes stories and keeps them for future reference.

-------
*keys:* In the above opera, a lady dies from a disease. Her lover reaches to her in the last 10 minutes.

/A story is about significant events and memorable moments, not about time passing. Duration neglect is normal in a story, and the ending often defines its character./

- duration neglect
- time passing
- significant events and memorable moments
-------

It is not only at the opera that we think of life as a story and wish it to end well. When we hear about the death of a woman who had been estranged from her daughter for many years, we want to know whether they were reconciled as death approached. We do not care only about the daughter’s feelings—it is the narrative of the mother’s life that we wish to improve. Caring for people often takes the form of concern for the quality of their stories, not for their feelings. Indeed, we can be deeply moved even by events that change the stories of people who are already dead. We feel pity for a man who died believing in his wife’s love for him, when we hear that she had a lover for many years and stayed with her husband only for his money. We pity the husband although he had lived a happy life. We feel the humiliation of a scientist who made an important discovery that was proved false after she died, although she did not experience the humiliation. Most important, of course, we all care intensely for the narrative of our own life and very much want it to be a good story, with a decent hero.

------
1. Caring for people often takes the form of concern for the quality of their stories, not for their feelings.
2. We feel the humiliation of a scientist who made an important discovery that was proved false after she died, although she did not experience the humiliation. 
-----   

The psychologist Ed Diener and his students wondered whether duration neglect and the peak-end rule would govern evaluations of entire lives. They used a short description of the life of a fictitious character called Jen, a never-married woman with no children, who died instantly and painlessly in an automobile accident. In one version of Jen’s story, she was extremely happy throughout her life (which lasted either 30 or 60 years), enjoying her work, taking vacations, spending time with her friends and on her hobbies. Another version added 5 extra years to Jen’s life, who now died either when she was 35 or 65. The extra years were described as pleasant but less so than before. After reading a schematic biography of Jen, each participant answered two questions: “Taking her life as a whole, how desirable do you think Jen’s life was?” and “How much total happiness or unhappiness would you say that Jen experienced in her life?”

-----
1. duration neglect
2. peak-end rule
3. The above two governing evaluations of entire lives

   The above:  life of a fictitious character called Jen
------   

The results provided clear evidence of both duration neglect and a peak-end effect. In a between-subjects experiment (different participants saw different forms), doubling the duration of Jen’s life had Jto Aad Jto no effect whatsoever on the desirability of her life, or on judgments of the total happiness that Jen experienced. Clearly, her life was represented by a prototypical slice of time, not as a sequence of time slices. As a consequence, her “total happiness” was the happiness of a typical period in her lifetime, not the sum (or integral) of happiness over the duration of her life.

------

In the above her 'total happiness' was the happiness of a typical period in her lifetime, not the sum of happiness over the duration of her life.

------

As expected from this idea, Diener and his students also found a less-is-more effect, a strong indication that an average (prototype) has been substituted for a sum. Adding 5 “slightly happy” years to a very happy life caused a substantial drop in evaluations of the total happiness of that life.

*key:* less-is-more effect

At my urging, they also colleected data on the effect of the extra 5 years in a within-subject experiment; each participant made both judgments in immediate succession. In spite of my long experience with judgment errors, I did not believe that reasonable people could say that adding 5 slightly happy years to a life would make it substantially worse. I was wrong. The intuition that the disappointing extra 5 years made the whole life worse was overwhelming.

-------

In the above year: If a person lives 50 years with great happiness. then people say him 'happy'. but if in the story only 2 years of harship are added then people decide his happiness on the basis of those last 2 years.

--------

The pattern of judgments seemed so absurd that Diener and his students initially thought that it represented the folly of the young people
who participated in their experiments. However, the pattern did not change
when the parents and older friends of students answered the same
questions. In intuitive evaluation of entire lives as well as brief episodes,
peaks and ends matter but duration does not.

*key:* peaks and ends matter but duration does not.

But the above concept seems not true when we do hard work at something or we spend good time in our holidays. Here /duration/ matters. We do not have /duration neglect/ rule:

The pains of labor and the benefits of vacations always come up as
objections to the idea of duration neglect: we all share the intuition that it is
much worse for labor to last 24 than 6 hours, and that 6 days at a good
resort is better than 3. Duration appears to matter in these situations, but
this is only because the quality of the end changes with the length of the
episode. The mother is more depleted and helpless after 24 hours than
after 6, and the vacationer is more refreshed and rested after 6 days than
after 3. What truly matters when we intuitively assess such episodes is the
progressive deterioration or improvement of the ongoing experience, and
how the person feels at the end.

*key:* In the above quality of the end changes with the length of the episode. If two persons spend 3 and 6 days in holidays respectively. At the end person II will be more relaxed because the /length of the episode/ has changed the /quality of the end/.

TODO

* Speaking of Life as a Story
- “He is desperately trying to protect the narrative of a life of integrity, which is endangered by the latest episode.”
- “The length to which he was willing to go for a one-night encounter is a sign of total duration neglect.”
- “You seem to be devoting your entire vacation to the construction of memories. Perhaps you should put away the camera and enjoy the moment, even if it is not very memorable?”
- “She is an Alzheimer’s patient. She no longer maintains a narrative of her life, but her experiencing self is still sensitive to beauty and gentleness.”
