#+TITLE: The Seven Laws of Mental Mastery
#+DATE: 2022-03-20T20:36:22
#+categories[]: emacs hugo org-mode
#+lastmod: [2022-03-21 Mon 12:37]
#+tags[]: mental mastery laws

#+CAPTION: This is my caption
#+ATTR_HTML: :class table table-striped table-dark
| Key | Value                |
| 1,2 | Jim Butters was here |


Mental laws, although their physical effects cannot be seen quite so easily, also work 100 percent of the time. Whenever your life is going well, it means that your thoughts and activities are aligned and in harmony with these invisible mental laws. Whenever you are having problems of any kind, it is almost invariably because you are violating one or more of these laws, whether you know about them or not. Because they are central to your happiness, it is essential that you become familiar with them and integrate them into everything you do.

1. THE LAW OF CONTROL
2. THE LAW OF CAUSE AND EFFECT
3. THE LAW OF BELIEF
4. THE LAW OF EXPECTATIONS
5. THE LAW OF ATTRACI10N
6. THE LAW OF CORRESPONDENCE
7. THE LAW OF MENTAL EQUIVALENCY

** (1) The Law of Control

   The Law of Control says that you feel positive about yourself to the degree to which you feel you are in control of your own life, and you feel negative about yourself to the degree to which you feel that you are not in control, or that you are controlled by some external force, person or influence.

This law or principle is widely recognized in psychology. It is called /"locus of control"/ theory. It is generally agreed that most stress, anxiety, tension and psychosomatic illness comes about as a result of the person feeling out of control, or not in control of some important part of his life.   

*Q:* Give an example to explain the /law of control/?    

*Ans:* For example, if you feel that your life is controlled by your debts, or your boss, or your ill health, or a bad relationship, or the behavior of others, you will suffer stress. This stress will manifest itself in irritation, anger, and resentment. If not dealt with, it can progress to insomnia, depression or illness of various kinds.

*Q:* How can you take control of your life?

*Ans:* In every case, control over your life begins with your thoughts, the only thing over which you do have complete control. How you think about any situation determines how you feel, and your feelings detennine your behavior.


#+BEGIN_QUOTE
If you have control on your thoughts, then you can take control over your feelings and then your behavior.

thoughts -> feelings -> behavior
#+END_QUOTE

*Notes:* Flash cards can be used to replace negative thoughts with positive thoughts. Then negative thoughts will not come if they come to you naturally.

*Q:* How does your thinking make you the controller of a situation?

Self-discipline, self-mastery, self-control all begin with you taking control of your thinking. No person or situation can make you feel anything-it is only the way you think about a situation that makes you feel the way you do. And you can control the way you think. As Eleanor Roosevelt said, "No one can make you feel inferior without your consent."

*Q:* What are the two ways to get control of a situation?

There are basically two ways you can get control of any situation that is causing you stress or unhappiness.

1. First, you can take action. You can move forward and do something to change it. You can assert yourself in the situation and make it different somehow.
2. And second, you can simply walk away. You can often regain control by letting go of a person or situation and getting busy doing something else.
   
Sometimes the very best thing to do in a situation if you feel out of control is just to leave. If you have ever ended an unhappy relationship or quit an unpleasant job, you will remember how much better you felt when you stopped struggling. By deciding not to resist anymore, you took back your sense of control.

*Q:* Why is it so important to be decisive?

The law of control explains why it is so important for you to be decisive. It explains why it is so important for you to know exactly what you want. The self-confidence that comes with feeling in control is why a person with a clear purpose and a plan always has an edge over someone who  is vague or unsure.

Examine the various areas of your life with a mental checklist and decide where you feel positive and in control, and where you don't. Then begin thinking of the specific things you could do to get control in those parts of your life causing you stress. Think also of the situations you might be better off walking away from.

One of your major responsibilities is to get and keep your life under control. This sense of control becomes your foundation for building greater happiness and success in the future. Make sure it's rock solid.

** (2) The Law of Cause and Effect

The Law of Cause and Effect says that for every effect in your life there is a specific cause. It is so important it has been called the "Iron Law of the Universe." It says that everything happens for a reason, whether or not you know what it is. There are no accidents. We live in an orderly universe governed strictly by law, and this understanding is central to every other law or principle.

The Law of Cause and Effect says that there are specific causes of success and there are specific causes of failure. There are specific causes for health and for illness. There are specific causes for happiness and for unhappiness. If there is an effect in your life that you want more of, you merely need to trace it back to the causes and repeat the causes. If there is an effect in your life that you do not enjoy, you need to trace it back to the causes and get rid of them.

TODO

*Q* What is the cause of your present condition?

The most important application of the Law of Cause and Effect, or sowing and reaping, is this: "Thoughts are causes and conditions are effects."

Your thoughts are the primary causes of the conditions of your life. Everything in your experience has begun with a thought of some kind, yours or someone else's.

Everything you are or ever will be, will be as a result of the way you think. If you change the quality of your thinking, you change the quality of your life. The change in your outer experience will follow the change in your inner experience. You will reap what you sow. You are doing it right now.


#+BEGIN_QUOTE
/Change the quality of your thinking, and you can change the quality of your life./
#+END_QUOTE


The beauty of this immutable law is that by accepting it, you take full control over your thinking, your feelings and your results. By applying the Law of Cause and Effect, you bring yourself into harmony with the Law of Control. You immediately feel better and happier about yourself.

Every aspect of business success or failure can be explained by this basic law. If you sow the right causes, you reap the desired effects. If you produce quality products or services that customers want and need and are willing to pay for, and then promote them vigorously, you'll be successful in selling them. If you don't, you won't.

If you do high-quality work and achieve the results that your company needs to grow and prosper, you'll be successful and happy in your career. If you treat others well, they'll treat you well. You'll always get out of life what you put in-and you control what you put in.





