#+TITLE: Chapter 3: The Master Program
#+DATE: 2022-03-21T18:33:25+0530
#+DRAFT: true

Everything that happens to you, everything you become and accomplish is determined by the way you think, by the way you use your mind. As you begin changing your mind, you begin changing your life. But how did you get to where you are today? What formati'le influences have combined to make you the person you are right now? Why do you think and feel the way you do, and what are the factors that have brought you to your current situation?

In this chapter, you will learn about your "master program" and how you have been put on a form of autopilot, starting from an early age. You will learn how to begin taking control of your internal guidance system, and how to remove influences and obstacles that have been interfering with your happiness without your even knowing about it. You will learn how to alter your master program to make it more consistent with the results you want.

When I was twenty, I was living in a small apartment with no job. It was the middle of winter and it was thirty-five degrees below zero. I was alone in a new city, thousands of miles from where I grew up.

Eleven years later, when I was thirty-one, I was again living alone in a small apartment. Again it was cold outside, thirty-five degrees below zero. I was deeply in debt, unemployed and a thousand miles from my family and friends.

After eleven years of working and traveling very little had changed. I was older and wiser but I still felt that I was spinning my wheels.

TODO

*SEVEN WAYS TO CONTROL YOUR MENTAL LIFE*

There is a series of actions you can take every day to saturate your mind with positive influences and to assure that you are continually bombarding yourself with suggestions that are consistent with the person you want to become.

Think about yourself, in a casual and relaxed way, as the person you would like to be, with the qualities you would like to have. Begin imagining what /life/ would be like, what your /home/ would be like, what your /work/ would be like, what your /health/ would be like, and the /standard of living/ that you would most enjoy. Allow yourself to fantasize and luxuriate in the daydream and in the feeling of achieving your goals. This activity is the first signal that a new direction is being programmed into your subconscious computer.

1. Visualization
2. Affirmations
3. Verblization
4. Acting the Part
5. Feeding Your Mind
6. Associating with Positive People
7. Teaching Others

*(1) Visualization*

Your visual images become your reality.

TODO

Most successful people have developed this ability, through practice, to create clear, vivid mental pictures of themselves being the persons and doing the things they really want. And since your external performance is always consistent with your internal image or picture, if you see yourself as an excellent parent, spouse, executive or salesperson, you will feel more relaxed, confident and capable in that role. If you see yourself as awkward or clumsy in any role, you will feel tense and uneasy whenever you find yourself in that particular situation.


*ACTION EXERCISE*

Select one positive habit pattern or behavior that you would like to develop, and for the next twenty-one days, discipline yourself to think, visualize, verbalize, affirm and behave in a manner consistent with the new habit you want to develop.

Whatever your goals and ambitions, think and talk in terms of their accomplishment. Read, learn, visualize, affirm and dwell on your goal. Think in terms of "how" you can achieve it. Act as if it were already a reality, if you can. At the very least, behave in every respect as if achieving your goal were inevitable.

The key to making these methods work for you is for you to demonstrate to yourself, in a specific area, that you can develop one important habit or attitude of your own choosing. Once you have proved this to yourself, you will have the self-confidence and the conviction to make any change or to accomplish any goal that you could set for yourself. Instead of wishing or hoping, you will know that your possibilities are unlimited.


